In [39]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [40]:
dataset = pd.read_csv('titanic/train.csv')
dataset.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [41]:
dataset.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [42]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


#### Dropping Columns which are not useful

In [43]:
columns = ['PassengerId', 'Name', 'Ticket', 'Cabin']
dataset.drop(columns, axis=1, inplace=True)

In [44]:
dataset.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [45]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    object 
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Fare      891 non-null    float64
 7   Embarked  889 non-null    object 
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB


#### we can observe that Age, Cabin, Embarked have missing values in them

In [46]:
dataset['Age'] = dataset['Age'].interpolate()

In [47]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    object 
 3   Age       891 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Fare      891 non-null    float64
 7   Embarked  889 non-null    object 
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB


In [48]:
dataset['Embarked'].fillna(dataset['Embarked'].mode()[0], inplace=True)

In [49]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    object 
 3   Age       891 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Fare      891 non-null    float64
 7   Embarked  891 non-null    object 
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB


#### Now lets deal with Categorical Values and convert them to numberical 

In [50]:
dataset.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [51]:
dummies = []
cols = ['Pclass', 'Sex', 'Embarked']
for col in cols:
    dummies.append(pd.get_dummies(dataset[col]))
titanic_dummies = pd.concat(dummies, axis=1)
titanic_dummies

1  2  3  female  male  C  Q  S
0    0  0  1       0     1  0  0  1
1    1  0  0       1     0  1  0  0
2    0  0  1       1     0  0  0  1
3    1  0  0       1     0  0  0  1
4    0  0  1       0     1  0  0  1
..  .. .. ..     ...   ... .. .. ..
886  0  1  0       0     1  0  0  1
887  1  0  0       1     0  0  0  1
888  0  0  1       1     0  0  0  1
889  1  0  0       0     1  1  0  0
890  0  0  1       0     1  0  1  0

[891 rows x 8 columns]

In [52]:
df = pd.concat((dataset, titanic_dummies),axis=1)

In [53]:
df.drop(cols, axis=1,inplace=True)

In [54]:
df

Survived   Age  SibSp  Parch     Fare  1  2  3  female  male  C  Q  S
0           0  22.0      1      0   7.2500  0  0  1       0     1  0  0  1
1           1  38.0      1      0  71.2833  1  0  0       1     0  1  0  0
2           1  26.0      0      0   7.9250  0  0  1       1     0  0  0  1
3           1  35.0      1      0  53.1000  1  0  0       1     0  0  0  1
4           0  35.0      0      0   8.0500  0  0  1       0     1  0  0  1
..        ...   ...    ...    ...      ... .. .. ..     ...   ... .. .. ..
886         0  27.0      0      0  13.0000  0  1  0       0     1  0  0  1
887         1  19.0      0      0  30.0000  1  0  0       1     0  0  0  1
888         0  22.5      1      2  23.4500  0  0  1       1     0  0  0  1
889         1  26.0      0      0  30.0000  1  0  0       0     1  1  0  0
890         0  32.0      0      0   7.7500  0  0  1       0     1  0  1  0

[891 rows x 13 columns]

#### Dividing dataset into independent(X) and dependent(y) variabls

In [55]:
X = df.drop('Survived',axis=1).values
y = df['Survived'].values

In [56]:
X

array([[22. ,  1. ,  0. , ...,  0. ,  0. ,  1. ],
       [38. ,  1. ,  0. , ...,  1. ,  0. ,  0. ],
       [26. ,  0. ,  0. , ...,  0. ,  0. ,  1. ],
       ...,
       [22.5,  1. ,  2. , ...,  0. ,  0. ,  1. ],
       [26. ,  0. ,  0. , ...,  1. ,  0. ,  0. ],
       [32. ,  0. ,  0. , ...,  0. ,  1. ,  0. ]])

In [57]:
y

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,

#### Train Test Split of Dataset

In [58]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((712, 12), (179, 12), (712,), (179,))

#### Standardization of data

In [59]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [60]:
X_train_scaled

array([[ 1.15978489, -0.47072241, -0.47934164, ..., -0.46146201,
        -0.30335547,  0.59248936],
       [-0.47160535, -0.47072241, -0.47934164, ..., -0.46146201,
        -0.30335547,  0.59248936],
       [ 0.18095074, -0.47072241, -0.47934164, ..., -0.46146201,
        -0.30335547,  0.59248936],
       ...,
       [ 0.83350684,  1.23056874, -0.47934164, ..., -0.46146201,
        -0.30335547,  0.59248936],
       [-1.12416145,  0.37992316,  2.04874166, ..., -0.46146201,
        -0.30335547,  0.59248936],
       [-0.61661782, -0.47072241,  0.78470001, ..., -0.46146201,
        -0.30335547,  0.59248936]])

In [61]:
X_test_scaled

array([[-0.47160535,  0.37992316,  0.78470001, ...,  2.16702561,
        -0.30335547, -1.68779402],
       [ 0.10844451, -0.47072241, -0.47934164, ..., -0.46146201,
        -0.30335547,  0.59248936],
       [-0.68912405, -0.47072241, -0.47934164, ..., -0.46146201,
        -0.30335547,  0.59248936],
       ...,
       [ 0.61598814,  0.37992316,  5.8408666 , ..., -0.46146201,
        -0.30335547,  0.59248936],
       [-0.90664275, -0.47072241, -0.47934164, ..., -0.46146201,
        -0.30335547,  0.59248936],
       [-1.84922377,  0.37992316,  0.78470001, ..., -0.46146201,
        -0.30335547,  0.59248936]])

#### Apply Principal Component Analysis to find best features

In [62]:
from sklearn.decomposition import PCA
pca = PCA()
pca.fit(X_train_scaled)
explained_variance_ratio = pca.explained_variance_ratio_
cumulative_variance_ratio = np.cumsum(explained_variance_ratio)
cumulative_variance_ratio

array([0.21925542, 0.39393338, 0.55776658, 0.68203505, 0.7819591 ,
       0.86340345, 0.92281388, 0.96724027, 1.        , 1.        ,
       1.        , 1.        ])

- We can see that only first 8 compenents captures almost all variance of dataset so we will take first 9 principal component

In [63]:
from sklearn.decomposition import PCA
pca = PCA(n_components=8)
X_train_pca = pca.fit_transform(X_train_scaled)
X_test_pca = pca.transform(X_test_scaled)

In [64]:
X_train_pca.shape, X_test_pca.shape, y_train.shape, y_test.shape

((712, 8), (179, 8), (712,), (179,))

### Now lastly lets use Logistic Regression Algorithm to make our predictive model

In [65]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression()
clf.fit(X_train_pca, y_train)
y_pred = clf.predict(X_test_pca)

In [66]:
from sklearn.metrics import confusion_matrix, accuracy_score
print(accuracy_score(y_pred=y_pred, y_true=y_test))
print(confusion_matrix(y_pred=y_pred, y_true=y_test))

0.7932960893854749
[[90 15]
 [22 52]]
